### ISSUE TITLE
倒计时的时候可以增加声音效果，就更好了

### ISSUE THREAD

**Issue by gannianyi** [Damon0820/vue-countdown#1]
倒计时的时候可以增加声音效果，就更好了

**Comment by Damon0820** [comment]
提议不错。方案：暴露接口（$emit事件），用户自行控制声音的播放。

**Comment by Damon0820** [comment]
> 倒计时的时候可以增加声音效果，就更好了

提议不错。方案：暴露接口（倒计时状态改变时，$emit事件），用户自行控制声音的播放。

**Comment by Damon0820** [comment]
> 倒计时的时候可以增加声音效果，就更好了

已暴露oNstatusChange方法
